using System.Collections.Generic;

// Container for deserialised map data
// Generated by http://json2csharp.com/

public class Layer
{
    public List<int> data { get; set; }
    public int height { get; set; }
    public string name { get; set; }
    public int opacity { get; set; }
    public string type { get; set; }
    public bool visible { get; set; }
    public int width { get; set; }
    public int x { get; set; }
    public int y { get; set; }
}

public class __invalid_type__121
{
    public double probability { get; set; }
}

public class __invalid_type__122
{
    public double probability { get; set; }
}

public class __invalid_type__123
{
    public double probability { get; set; }
}

public class __invalid_type__124
{
    public double probability { get; set; }
}

public class Tiles
{
    public __invalid_type__121 __invalid_name__121 { get; set; }
    public __invalid_type__122 __invalid_name__122 { get; set; }
    public __invalid_type__123 __invalid_name__123 { get; set; }
    public __invalid_type__124 __invalid_name__124 { get; set; }
}

public class Tileset
{
    public int columns { get; set; }
    public int firstgid { get; set; }
    public string image { get; set; }
    public int imageheight { get; set; }
    public int imagewidth { get; set; }
    public int margin { get; set; }
    public string name { get; set; }
    public int spacing { get; set; }
    public int tilecount { get; set; }
    public int tileheight { get; set; }
    public int tilewidth { get; set; }
    public Tiles tiles { get; set; }
}

public class RootObject
{
    public int height { get; set; }
    public List<Layer> layers { get; set; }
    public int nextobjectid { get; set; }
    public string orientation { get; set; }
    public string renderorder { get; set; }
    public int tileheight { get; set; }
    public List<Tileset> tilesets { get; set; }
    public int tilewidth { get; set; }
    public int version { get; set; }
    public int width { get; set; }
}
